import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";

export async function generateSjbPdf(form, logoDataUrl = null) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 40;

  const drawTitle = (text, y) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(text, margin, y);
    return y + 8;
  };

  const makeTable = (opts) => {
    autoTable(doc, {
      styles: { fontSize: 10, cellPadding: 6, overflow: "linebreak" },
      headStyles: { fillColor: [235, 245, 250], textColor: 20, halign: "left" },
      bodyStyles: { valign: "top" },
      theme: "grid",
      ...opts,
    });
  };

  if (logoDataUrl) {
    try { doc.addImage(logoDataUrl, "PNG", margin, 28, 120, 40); } catch {}
  }
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("SJBGroup INSPECTION REPORT", margin, 100);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Generated by KovaFlo • ${format(new Date(), "PPpp")}`, margin, 116);

  /* ---------------- Project ---------------- */
  makeTable({
    startY: 140,
    head: [["Field", "Value"]],
    body: [
      ["Project", form.projectName || ""],
      ["Operator / Contractor", form.client || ""],      // label updated
      ["Inspector", form.inspector || ""],
      ["Date", form.date || ""],
      ["Location", form.location || ""],
    ],
    columnStyles: { 0: { cellWidth: 160 }, 1: { cellWidth: pageW - margin * 2 - 160 } },
  });

  /* ---------------- Weather ---------------- */
  makeTable({
    startY: doc.lastAutoTable.finalY + 12,
    head: [["Weather", ""]],
    body: [
      ["Conditions", form.weather || ""],
      ["Temperature (°F)", form.temp || ""],
      ["Wind", form.wind || ""],
      ["Precipitation", form.precip || ""],
    ],
    columnStyles: { 0: { cellWidth: 160 }, 1: { cellWidth: pageW - margin * 2 - 160 } },
  });

  /* ---------------- Crew ---------------- */
  makeTable({
    startY: doc.lastAutoTable.finalY + 12,
    head: [["Crew Member", "Company", "Role"]],
    body: (form.crew || []).length
      ? form.crew.map(c => [c.name || "", c.company || "", c.role || ""])
      : [["—", "—", "—"]],
    columnStyles: { 0: { cellWidth: 180 }, 1: { cellWidth: 180 }, 2: { cellWidth: pageW - margin * 2 - 360 } },
  });

  /* ---------------- Equipment ---------------- */
  makeTable({
    startY: doc.lastAutoTable.finalY + 12,
    head: [["Equipment", "Qty"]],
    body: (form.equipment || []).length
      ? form.equipment.map(e => [e.type || "", e.qty || ""])
      : [["—", "—"]],
    columnStyles: { 0: { cellWidth: pageW - margin * 2 - 80 }, 1: { cellWidth: 80, halign: "center" } },
  });

  /* ---------------- Work Summary ---------------- */
  makeTable({
    startY: doc.lastAutoTable.finalY + 12,
    head: [["Work Summary"]],
    body: [[(form.summary || "").replace(/\r?\n/g, "\n") || ""]],
    columnStyles: { 0: { cellWidth: pageW - margin * 2 } },
  });

  /* ---------------- Pipe Installed ---------------- */
  makeTable({
    startY: doc.lastAutoTable.finalY + 12,
    head: [["Size", "Type", "Footage", "Serial #"]],
    body: (form.pipes || []).length
      ? form.pipes.map(p => [p.size || "", p.ptype || "", p.footage || "", p.serial || ""])
      : [["—", "—", "—", "—"]],
    columnStyles: { 0: { cellWidth: 80 }, 1: { cellWidth: 120 }, 2: { cellWidth: 100 }, 3: { cellWidth: pageW - margin * 2 - 300 } },
  });

  /* ---------------- Materials / Fittings ---------------- */
  makeTable({
    startY: doc.lastAutoTable.finalY + 12,
    head: [["Item", "Spec / Size", "Qty", "Notes"]],
    body: (form.materials || []).length
      ? form.materials.map(m => [m.item || "", m.spec || "", m.qty || "", m.notes || ""])
      : [["—", "—", "—", "—"]],
    columnStyles: { 0: { cellWidth: 160 }, 1: { cellWidth: 160 }, 2: { cellWidth: 60, halign: "center" }, 3: { cellWidth: pageW - margin * 2 - 380 } },
  });

  /* ---------------- Checkbox Sections ---------------- */
  const mark = (val, code) => (val === code ? "X" : "");
  const drawMatrix = (title, arr, codes, labels) => {
    const startY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 18 : 160;
    let y = drawTitle(title, startY);
    const head = ["Description", ...codes.map(c => labels[c] ?? c), "Ref"];
    const body = (arr || []).map(it => {
      const cells = [it.label || ""];
      codes.forEach(c => cells.push(mark(it.val, c)));
      cells.push(it.ref || "");
      return cells;
    });

    autoTable(doc, {
      startY: y + 6,
      head: [head],
      body: body.length ? body : [["—", ...codes.map(()=>"—"), "—"]],
      columnStyles: (() => {
        const descW = pageW - margin * 2 - (codes.length * 40) - 120;
        const styles = { 0: { cellWidth: Math.max(160, descW) } };
        codes.forEach((_, i) => { styles[i+1] = { cellWidth: 40, halign: "center" }; });
        styles[codes.length + 1] = { cellWidth: 120 };
        return styles;
      })(),
      showHead: "firstPage",
      pageBreak: "auto",
    });
  };

  const LBL = { Y: "Yes", N: "No", NA: "N/A", NO: "N/O" };
  drawMatrix("2 • Jobsite Safety Awareness / Knowledge", form.secSafety, ["Y","N"], LBL);
  drawMatrix("3 • Jobsite Permits",                 form.secPermits, ["Y","N","NA","NO"], LBL);
  drawMatrix("4 • General Construction Practices",  form.secGeneral, ["Y","N"], LBL);
  drawMatrix("5 • Plastic Pipe Installation",       form.secPlastic, ["Y","N","NA","NO"], LBL);
  drawMatrix("6 • Distribution Line Valves",        form.secValves,  ["Y","N","NA","NO"], LBL);
  drawMatrix("7 • Damage Prevention",               form.secDamage,  ["Y","N","NA","NO"], LBL);
  drawMatrix("8 • Meter Set Installed",             form.secMeter,   ["Y","N","NA","NO"], LBL);
  drawMatrix("9 • Job Site / Back Fill",            form.secBackfill,["Y","N","NA","NO"], LBL);
  drawMatrix("10 • Records",                         form.secRecords, ["Y","N","NA","NO"], LBL);

  /* ---------------- Photos ---------------- */
  const photos = Array.isArray(form.photos) ? form.photos : [];
  if (photos.length) {
    doc.addPage();
    doc.setFont("helvetica", "bold"); doc.setFontSize(14);
    doc.text("Photos", margin, margin);

    const cellW = (pageW - margin * 2 - 20) / 2;
    const cellH = 200;
    const captionH = 28;
    let col = 0, y = margin + 16;

    const addPhotoCell = (p, x, yPos) => {
      try {
        const iw = p.w || 1600, ih = p.h || 1200;
        const r = Math.min(cellW / iw, (cellH - captionH - 6) / ih);
        const w = Math.max(1, iw * r);
        const h = Math.max(1, ih * r);
        const xImg = x + (cellW - w) / 2;
        const yImg = yPos + 4;
        const fmt = (p.dataUrl || "").includes("image/png") ? "PNG" : "JPEG";
        doc.addImage(p.dataUrl, fmt, xImg, yImg, w, h);
        doc.setFont("helvetica", "normal"); doc.setFontSize(10);
        const cap = (p.caption || "").trim();
        if (cap) doc.text(cap, x + 4, yImg + h + 18, { maxWidth: cellW - 8 });
      } catch {}
    };

    photos.forEach((p) => {
      const x = margin + col * (cellW + 20);
      addPhotoCell(p, x, y);
      col++;
      if (col > 1) { col = 0; y += cellH; if (y + cellH > pageH - margin) {
        doc.addPage();
        doc.setFont("helvetica", "bold"); doc.setFontSize(14);
        doc.text("Photos (cont.)", margin, margin);
        y = margin + 16;
      }}
    });
  }

  // Footer note
  const h = doc.internal.pageSize.getHeight();
  doc.setFontSize(9); doc.setTextColor(120);
  doc.text("Generated by KovaFlo • sjb-inspection", margin, h - 28);

  const safeProj = (form.projectName || "project").toLowerCase().replace(/[^a-z0-9]+/g, "-");
  const safeDate = (form.date || "").replace(/[^0-9-]+/g, "");
  doc.save(`${safeProj}-${safeDate || "today"}-sjb-report.pdf`);
}
